"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see

https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from os.path import join
from pathlib import Path

import environ
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

env = environ.Env(
    # SECRET_KEY has no default — Django raises ImproperlyConfigured if missing.
    # Generate a value with:
    #   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["127.0.0.1", "localhost"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    # AWS / S3
    USE_S3=(bool, False),
    AWS_STORAGE_BUCKET_NAME=(str, ""),
    AWS_S3_REGION_NAME=(str, "us-east-1"),
    AWS_ACCESS_KEY_ID=(str, ""),
    AWS_SECRET_ACCESS_KEY=(str, ""),
    AWS_S3_CUSTOM_DOMAIN=(str, ""),
)

env.read_env(os.path.join(BASE_DIR, ".env"), overwrite=True)

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded strictly from the environment — no fallback, fails fast if unset.
SECRET_KEY = env("SECRET_KEY")

# Fernet keys for encrypting biometric device credentials at rest.
# django-fernet-fields reads this list; the first key encrypts new values,
# all keys are tried for decryption (enables zero-downtime key rotation).
# Generate a key with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
FERNET_KEYS = [env("FIELD_ENCRYPTION_KEY", default="")]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "notifications",
    "mathfilters",
    "corsheaders",
    "simple_history",
    "django_filters",
    "base",
    "employee",
    "recruitment",
    "leave",
    "pms",
    "onboarding",
    "asset",
    "attendance",
    "payroll",
    "widget_tweaks",
    "django_apscheduler",
]
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "horilla_api.middleware.RejectBasicAuthMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "horilla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if env("DATABASE_URL", default=None):
    DATABASES = {
        "default": {
            **env.db(),
            # Keep TCP connections alive for up to 60 s per worker thread.
            # Eliminates a TCP + TLS handshake (~5–15 ms) on every request.
            # Set to 0 to revert to a new connection per request (default).
            # Override via CONN_MAX_AGE env var, e.g. CONN_MAX_AGE=0 for pgBouncer.
            "CONN_MAX_AGE": env.int("CONN_MAX_AGE", default=60),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(
                    BASE_DIR,
                    "TestDB_Horilla.sqlite3",
                ),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
            # Keep TCP connections alive for up to 60 s per worker thread.
            # Eliminates a TCP + TLS handshake (~5–15 ms) on every request.
            # Set CONN_MAX_AGE=0 in .env when using an external connection
            # pooler (e.g. pgBouncer) to avoid connection ownership conflicts.
            "CONN_MAX_AGE": env.int("CONN_MAX_AGE", default=60),
        }
    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'horilla',       # database name
#         'USER': 'postgres',          # postgres user
#         'PASSWORD': 'cool',  # user password
#         'HOST': 'localhost',       # or IP address
#         'PORT': '5432',            # default postgres port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = env("MEDIA_ROOT", default=str(os.path.join(BASE_DIR, "media/")))

# ---------------------------------------------------------------------------
# Storage: S3 (production) vs local filesystem (development)
# ---------------------------------------------------------------------------
# Set USE_S3=True in your .env / ECS task definition environment variables
# to switch media file storage to AWS S3.  Static files always use WhiteNoise
# (served from the container) to avoid the cost of S3 GET requests per page.
# ---------------------------------------------------------------------------
USE_S3 = env("USE_S3")

if USE_S3:
    # AWS credentials (injected from Secrets Manager in production)
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")
    AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN") or \
        f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

    # Security: files not publicly readable by default
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_QUERYSTRING_AUTH = True   # signed URLs for private media
    AWS_S3_FILE_OVERWRITE = False  # never silently overwrite uploads

    # Media files → S3
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    # Static files → WhiteNoise (served from container, not S3)
    # This avoids extra S3 GET cost on every page request.
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
else:
    # Local development — serve everything from disk
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# ---------------------------------------------------------------------------
# pdfkit / wkhtmltopdf path
# ---------------------------------------------------------------------------
# macOS (Homebrew): /usr/local/bin/wkhtmltopdf
# Linux (apt / Docker image): /usr/bin/wkhtmltopdf
# Override with env var WKHTMLTOPDF_PATH if installed elsewhere.
# ---------------------------------------------------------------------------
import shutil as _shutil

WKHTMLTOPDF_PATH = os.environ.get(
    "WKHTMLTOPDF_PATH",
    _shutil.which("wkhtmltopdf") or "/usr/bin/wkhtmltopdf",
)
PDFKIT_CONFIG = {"wkhtmltopdf": WKHTMLTOPDF_PATH}
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------------------------------------------------
# Email / SMTP Configuration
# ---------------------------------------------------------------------------
# Primary approach: configure a mail server via Admin > Settings > Mail Servers.
# Fallback approach: set the variables below in your .env file to use a fixed
# SMTP configuration without creating a DB record.
#
# Horilla's custom backend reads DB config first, then falls back to these.
# ---------------------------------------------------------------------------
EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="base.backends.ConfiguredEmailBackend"
)
EMAIL_HOST = env("EMAIL_HOST", default=None)
EMAIL_PORT = env("EMAIL_PORT")          # int, default 587
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default=None)
EMAIL_USE_TLS = env("EMAIL_USE_TLS")    # bool, default True
EMAIL_USE_SSL = env("EMAIL_USE_SSL")    # bool, default False
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@horilla.com")

# ──────────────────────────────────────────────────────────────────────────────
# Django Cache — Redis backend (django-redis)
# ──────────────────────────────────────────────────────────────────────────────
# Install:  pip install django-redis
#
# Redis DB allocation
#   DB 0 — Celery broker + result backend  (CELERY_BROKER_URL / RESULT_BACKEND)
#   DB 1 — Django cache (this block)        ← keeps namespaces separate
#
# The KEY_PREFIX "horilla" is prepended to every cache key so that multiple
# Horilla instances sharing the same Redis server don't collide.
#
# COMPRESSOR — zlib is enabled for the "default" backend.  Dashboard stats
# serialise as small JSON dicts (<2 KB), so compression overhead is minimal
# and memory usage is reduced for larger cached values (e.g. recruitment data).
#
# SOCKET_CONNECT_TIMEOUT / SOCKET_TIMEOUT — if Redis is unavailable, Django
# will raise a cache error after 5 s rather than hanging indefinitely.
# Wrap cache calls with `try/except` or use `cache.get(key, default)` so a
# Redis outage degrades gracefully (falls back to recomputing from DB).
#
# SESSION_ENGINE / SESSION_CACHE_ALIAS — optional: uncomment to store Django
# sessions in Redis instead of the DB table.  Speeds up every authenticated
# request that touches the session.

_CACHE_REDIS_URL = env("CACHE_REDIS_URL", default="redis://localhost:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": _CACHE_REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Raise after N seconds instead of blocking indefinitely on connect.
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            # Re-raise a stale broken-pipe as a cache error so Django can
            # fall back to computing from DB rather than returning corrupt data.
            "RETRY_ON_TIMEOUT": True,
            # Cap the number of pooled connections.  Each Gunicorn worker has
            # its own pool; 20 connections × 9 workers = 180 total connections
            # which is well within Redis's default max of 10 000.
            "CONNECTION_POOL_KWARGS": {"max_connections": 20},
            # Serialiser — pickle is Django's default, json is safer but
            # requires values to be JSON-serialisable (no QuerySets, datetimes
            # must be converted to strings).  We use pickle here because some
            # dashboard values include Decimal / date objects.
            "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
        },
        "KEY_PREFIX": "horilla",
        # Default TTL for cache.set() calls that don't specify one.
        # Dashboard views override this with explicit timeout= arguments.
        "TIMEOUT": 300,
    },
}

# Uncomment to store Django sessions in Redis (faster than DB-backed sessions):
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# ──────────────────────────────────────────────────────────────────────────────
# Celery / Redis configuration
# ──────────────────────────────────────────────────────────────────────────────
# Set REDIS_URL in .env, e.g.: REDIS_URL=redis://localhost:6379/0
# For production with TLS:      REDIS_URL=rediss://:password@host:6380/0
_REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")

CELERY_BROKER_URL = _REDIS_URL
CELERY_RESULT_BACKEND = _REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = env("TIME_ZONE", default="Asia/Kolkata")
CELERY_ENABLE_UTC = True

# ── Reliability ───────────────────────────────────────────────────────────────
# Acknowledge only AFTER the task finishes.  If the worker crashes mid-task
# the message is re-queued for another worker to pick up.
CELERY_TASK_ACKS_LATE = True

# Track STARTED state so TaskProgress can move from PENDING → PROGRESS.
CELERY_TASK_TRACK_STARTED = True

# Prevent one slow worker from hoarding messages.  Each worker fetches one
# task at a time so bulk_processing workers don't starve high_priority ones.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Restart worker child process every N tasks to prevent pdfkit / wkhtmltopdf
# memory leaks from accumulating over a long-running worker.
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# ── Time limits ───────────────────────────────────────────────────────────────
# Soft limit sends SIGTERM → task can clean up.  Hard limit sends SIGKILL.
# Biometric sync: 5 min soft / 7 min hard.
# Payroll generation: 20 min soft / 25 min hard (1 000 employees × pdfkit).
CELERY_TASK_SOFT_TIME_LIMIT = env.int("CELERY_SOFT_TIME_LIMIT", default=300)
CELERY_TASK_TIME_LIMIT = env.int("CELERY_HARD_TIME_LIMIT", default=420)

# ── Result expiry ─────────────────────────────────────────────────────────────
# Keep task results in Redis for 24 h (progress bars are polled within that window).
CELERY_RESULT_EXPIRES = 86400

# ── Queue definitions ─────────────────────────────────────────────────────────
# kombu (installed with celery) provides explicit Queue/Exchange objects that
# let you set exchange types and priorities.  We guard the import so that
# `manage.py runserver` works even before `pip install celery` is run.
# Without this guard, a missing kombu crashes Django at settings-import time.
try:
    from kombu import Exchange, Queue  # noqa: F401

    CELERY_TASK_QUEUES = (
        # Biometric pings and urgent alerts — fast worker pool.
        Queue(
            "high_priority",
            Exchange("high_priority", type="direct"),
            routing_key="high_priority",
        ),
        # Monthly payroll generation, bulk PDF/Excel export — heavy, slow.
        Queue(
            "bulk_processing",
            Exchange("bulk_processing", type="direct"),
            routing_key="bulk_processing",
        ),
        # General catch-all for lightweight tasks.
        Queue(
            "default",
            Exchange("default", type="direct"),
            routing_key="default",
        ),
        # Dead-letter destination for tasks that exhaust all retries.
        # A dedicated worker consumes this queue so ops can inspect failures
        # without them being silently dropped.  NOT automatically retried.
        Queue(
            "dead_letter",
            Exchange("dead_letter", type="direct"),
            routing_key="dead_letter",
        ),
    )
except ImportError:
    # Celery / kombu not installed yet — Django still boots normally.
    # The queue names defined in CELERY_TASK_ROUTES below are enough for
    # Celery to create the queues automatically on first worker start.
    pass

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "default"

# ── Per-task routing ──────────────────────────────────────────────────────────
CELERY_TASK_ROUTES = {
    # Biometric → high_priority
    "biometric.tasks.sync_biometric_device": {"queue": "high_priority"},
    "biometric.tasks.sync_all_biometric_devices": {"queue": "high_priority"},
    # Payroll bulk operations → bulk_processing
    "payroll.tasks.generate_monthly_payroll": {"queue": "bulk_processing"},
    "payroll.tasks.process_single_employee_payslip": {"queue": "bulk_processing"},
    "payroll.tasks.bulk_export_payslip_pdf": {"queue": "bulk_processing"},
    "payroll.tasks.finalize_payroll_batch": {"queue": "bulk_processing"},
}

# ── Beat periodic schedule (replaces APScheduler) ────────────────────────────
# Add django-celery-beat to INSTALLED_APPS and run:
#   python manage.py migrate django_celery_beat
# Then these schedules are stored in the DB and editable via Django admin.
#
# from celery.schedules import crontab
# CELERY_BEAT_SCHEDULE = {
#     "auto-payslip-generate": {
#         "task": "payroll.tasks.auto_payslip_generate",
#         "schedule": crontab(minute=0, hour="*/3"),
#     },
#     "expire-contracts": {
#         "task": "payroll.tasks.expire_contracts",
#         "schedule": crontab(minute=0, hour="*/4"),
#     },
#     "sync-all-biometric-devices": {
#         "task": "biometric.tasks.sync_all_biometric_devices",
#         "schedule": crontab(minute="*/30"),
#     },
# }

MESSAGE_TAGS = {
    messages.DEBUG: "oh-alert--warning",
    messages.INFO: "oh-alert--info",
    messages.SUCCESS: "oh-alert--success",
    messages.WARNING: "oh-alert--warning",
    messages.ERROR: "oh-alert--danger",
}


CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

LOGIN_URL = "/login"


SIMPLE_HISTORY_REVERT_DISABLED = True


DJANGO_NOTIFICATIONS_CONFIG = {
    "USE_JSONFIELD": True,
    "SOFT_DELETE": True,
    "USE_WATCHED": True,
    "NOTIFICATIONS_STORAGE": "notifications.storage.DatabaseStorage",
    "TEMPLATE": "notifications.html",  # Add this line
}

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGES = (
    ("en", "English (US)"),
    ("de", "Deutsche"),
    ("es", "Español"),
    ("fr", "Français"),
    ("ar", "عربى"),
    ("pt-br", "Português (Brasil)"),
    ("zh-hans", "Simplified Chinese"),
    ("zh-hant", "Traditional Chinese"),
    ("it", "Italian"),
)


LOCALE_PATHS = [
    join(BASE_DIR, "horilla", "locale"),
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE", default="Asia/Kolkata")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ── Django REST Framework ─────────────────────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "horilla_api.auth.SwaggerAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon":      "100/day",
        "user":      "1000/day",
        "login":     "5/minute",
        "login_day": "20/day",
    },
}

# Production settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
